apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argo-bot.fullname" . }}
  labels:
    {{- include "argo-bot.labels" . | nindent 4 }}
type: Opaque
data:
  DEPLOY_GITHUB_AUTH_APP_ID: {{ .Values.github.appId | toString | b64enc }}
  DEPLOY_GITHUB_AUTH_INSTALLATION_ID: {{ .Values.github.installationId | toString | b64enc }}
  DEPLOY_GITHUB_AUTH_KEY_PATH: {{ printf "%s/%s" .Values.github.privateKeyMountPath .Values.github.privateKeyFilename | b64enc }}
  SLACK_APP_TOKEN: {{ .Values.slack.appToken | b64enc }}
  SLACK_BOT_TOKEN: {{ .Values.slack.botToken | b64enc }}
