apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  labels:
    app: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: "cr.example.com/users-service:{{ .Version}}"
          imagePullPolicy: IfNotPresent
          env:
            - name: "ENVIRONMENT"
              value: "{{ .Environment }}"
            - name: "RABBITMQ_URL"
              value: "rabbitmq.staging.internal.example.com"
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: users-service
