apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
  namespace: "{{ .Environment }}"
  labels:
    app: accounts-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-service
  template:
    metadata:
      labels:
        app: accounts-service
    spec:
      containers:
        - name: accounts-service
          image: "cr.example.com/accounts-service:{{ .Version}}"
          imagePullPolicy: IfNotPresent
          env:
            - name: "ENVIRONMENT"
              value: "{{ .Environment }}"
            - name: "INGRESS_PATH"
              value: "{{ .Service }}.{{ .Environment }}.internal.example.com"
