apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: "prod"
  labels:
    app: accounts-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: accounts-service
